spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/midb
    username: admin
    password: Celinm08
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect


  security:
    jwt:
      secret-key: gdQldjQ+y+e5MqO69sq7YEOBSK7u/IKHM/jlQ+rFg0I
      expiration: 86400000
      refresh-token:
        expiration: 100000000000
    user:
      name: juanda
      password: jijoxd